[
    {
        "Date": "",
        "Build": "",
        "Setup": "",
        "Result": "",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43669.0,
        "Build": "2.2.0(89)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "E2E Daily Sanity failed as the node appserv54 was inaccessible through management and ipmi. It was turned up today so the next sanity should run as usual.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43670.0,
        "Build": "9.9.1 (38)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "E2E Daily Sanity failed due to the TC: Network.PingExternalIP with the TestFailed Error: Pod \"e2e-test-pod\" is not in running state. The failure cause by recent dev changes.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43673.0,
        "Build": "9.9.1 (42)",
        "Setup": "appserv53,54,55",
        "Result": "Passed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "E2E Daily Sanity passed with the following skiplist: Cluster.AddNodes Management | Cluster.FailedNodes Management | Cluster.RecommissionNode | Management Cluster.RemoveNodeWithPods Management | Volume.CheckStorageReservation Management",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43675.0,
        "Build": "9.9.1 (44-2)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43707.0,
        "Build": "9.9.1 (47)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5673",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Namespace got deleted after updating group",
        "Current Owner of Sanity": "KiranZ"
    },
    {
        "Date": 43678.0,
        "Build": "9.9.1 (50)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5673",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Namespace got deleted after updating group",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43679.0,
        "Build": "9.9.1 (51-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "-",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Cluster destroy took longer time. But e2e gave up before that.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43681.0,
        "Build": "9.9.1 (54-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "-",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Aborted.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43682.0,
        "Build": "9.9.1 (55-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-3713",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "E2e test case issue.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43683.0,
        "Build": "9.9.1 (57-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5460",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "There were some stale resources [like iops, remote-controllers, bandwidth] in cluster status, even though there were not volumes/ snapshot on cluster.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43684.0,
        "Build": "9.9.1 (59-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "-",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Cluster destroy took longer time. But e2e gave up before that.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43686.0,
        "Build": "9.9.1 (65-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-3713",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Network.ValidateTrafficAfterIperfClientRcPodEvacuation need to be fixed. For now add this test case in skip list.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43687.0,
        "Build": "9.9.1 (67-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-3713",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Network.ValidateTrafficAfterIperfClientRcPodEvacuation need to be fixed. For now add this test case in skip list.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43688.0,
        "Build": "9.9.1 (69-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "-",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Bharati destroied cluster by mistake while sanity was running.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43689.0,
        "Build": "9.9.1 (72-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5722",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Hit rare case in e2e code. E2e was expecting plexes of a volume in resyning state. But resync on volume had completed on volume, before e2e was checking if plexes of volume were in resyning state.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43692.0,
        "Build": "9.9.1 (75-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5720, DWS-5747",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Failed to configure snmp receiver, Storage resources didn't get cleaned-up after volume deletion",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "",
        "Build": "",
        "Setup": "",
        "Result": "",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "",
        "Build": "",
        "Setup": "",
        "Result": "",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43701.0,
        "Build": "9.9.1(93-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Automation code issue in Tc \"Cluster.RemoveTwoQuorumNodesFromThreeNodeCluster\". Yogesh is going to fix this in his next checkin.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43702.0,
        "Build": "9.9.1(95-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5720",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Failed to configure snmp receiver",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43703.0,
        "Build": "9.9.1(95-1)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5720",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Failed to configure snmp receiver",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43704.0,
        "Build": "9.9.1(96-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Automation code issue in TC \"VolumeResize.PatternVerificationOnResizedMirroredVolumesAfterReboot\". Rajat will fix this in his next checkin.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43706.0,
        "Build": "9.9.1(100-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5460",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Cluster status showed stale storage resources.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43707.0,
        "Build": "9.9.1(101-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5764",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Network resource not released after deleting all pods.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43708.0,
        "Build": "9.9.1(103-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Automation code issue in Snapshot.MkfsOnVolSnapLcvCreateCksumVerification. Kiran Kothule is going to fix it.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43709.0,
        "Build": "9.9.1(105-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5798",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "csi-diamanti-driver-bd8sp pod remained in ContainerCreating state.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43709.0,
        "Build": "9.9.1(105-1)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5798",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "csi-diamanti-driver-bd8sp pod remained in ContainerCreating state.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43710.0,
        "Build": "9.9.1(105-2)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5798",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "csi-diamanti-driver-bd8sp pod remained in ContainerCreating state.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43711.0,
        "Build": "",
        "Setup": "",
        "Result": "",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Setup Given in failed state for DWS-5799",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43712.0,
        "Build": "9.9.1(107-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5804",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Convoy Panic",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43713.0,
        "Build": "9.9.1(110-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "appserv53 did not come up after reboot.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43713.0,
        "Build": "9.9.1(110-3)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5464",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Remote user login failed.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43714.0,
        "Build": "9.9.1(110-4)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5842",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Volume remained in pending state because appserv53 went into Notready state.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43716.0,
        "Build": "9.9.1(112-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5839",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Automation bug in pod spreading check.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "",
        "Build": "",
        "Setup": "",
        "Result": "",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43718.0,
        "Build": "9.9.1(115-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5832",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Armada restarted while trying to acquire Master lock.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43719.0,
        "Build": "9.9.1(116-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "User error. Setup was used for 2 node cluster.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43719.0,
        "Build": "9.9.1(116-1)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5838",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Convoy stopped due to EOF error and restarted on another node.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43720.0,
        "Build": "9.9.1(118-1)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5838",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Convoy stopped due to EOF error and restarted on another node.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43721.0,
        "Build": "",
        "Setup": "",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "testserver 3 rebooted",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43722.0,
        "Build": "9.9.1(121-3)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5460",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Cluster status showed stale storage resources.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43723.0,
        "Build": "9.9.1(124-1)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5838",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Convoy stopped due to EOF error and restarted on another node.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43724.0,
        "Build": "9.9.1(125-1)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5838",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Convoy stopped due to EOF error and restarted on another node.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43724.0,
        "Build": "9.9.1(125-3)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5853",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Armada panic",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43726.0,
        "Build": "9.9.1(128-3)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Other e2e interrupted the this e2e test.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43727.0,
        "Build": "9.9.1(129-3)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Fio command failed. appserv53 rebooted.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43728.0,
        "Build": "9.9.1(129-3)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Aborted by Naveen for running Sanity on k8s1.15.3 build rpm",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43729.0,
        "Build": "9.9.1(134-3)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5720",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Failed to configur SNMP",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43730.0,
        "Build": "9.9.1(135-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43731.0,
        "Build": "9.9.1(136-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-3953",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Error while changing preferred plex. Volume plex state was different on management and embedded side.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43732.0,
        "Build": "9.9.1(136-2)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "DWS-5838",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Convoy stopped due to EOF error.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43733.0,
        "Build": "9.9.1(139-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Another test (Sanity tagged e2e ) started on the same setup.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43734.0,
        "Build": "9.9.1(141-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "admin user login failed because no space left on testserver3.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43735.0,
        "Build": "9.9.1(144-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "admin user login failed because no space left on testserver3.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43736.0,
        "Build": "9.9.1(147-0)",
        "Setup": "appserv53,54,55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Somebody used the setup when e2e was running.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43739.0,
        "Build": "9.9.1(146-1)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5683",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Pod \"csi-external-attacher-0\" goes into CrashLoopBackOff",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43744.0,
        "Build": "9.9.1(159-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-3080",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Failed during e2e weekly test Mirroring.LargeSizeVolumesRebootTestWithVerification, ssh time out, connection refused",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43745.0,
        "Build": "9.9.1(163-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5951",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Cluster login failed, convoy was down",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43747.0,
        "Build": "9.9.1(165-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5683",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Pod \"csi-external-provisioner-0\" goes into CrashLoopBackOff",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43747.0,
        "Build": "9.9.1(165-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5683",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Pod \"csi-external-resizer-0\" goes into CrashLoopBackOff",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43747.0,
        "Build": "9.9.1(166-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-3080",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Failed during e2e weekly test Mirroring.LargeSizeVolumesRebootTestWithVerification, ssh time out, connection refused",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43748.0,
        "Build": "9.9.1(166-2)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5935",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "QoS not honorred because of unexpected prometheus repsense  ",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43747.0,
        "Build": "9.9.1(170-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5683",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Pod \"csi-external-attacher-0\" goes into CrashLoopBackOff",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43748.0,
        "Build": "9.9.1(173-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5935",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "QoS not honorred because of unexpected prometheus repsense  ",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43748.0,
        "Build": "9.9.1(173-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5974",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "After deleting pods, VNICs used by pods are not freed.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43752.0,
        "Build": "9.9.1(176-1)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5974",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "After deleting pods, VNICs used by pods are not freed.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43753.0,
        "Build": "9.9.1(177-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-4904",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Embedded not reachable.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43753.0,
        "Build": "9.9.1(177-3)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5994",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Failure while generating device list, Failed to get device path, convoy stopped.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43753.0,
        "Build": "9.9.1(177-1)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5995",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Cluster destroy failed",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43753.0,
        "Build": "9.9.1(177-2)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Failed to run sanity, nodes were not reachable",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43753.0,
        "Build": "9.9.1(179-1)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5997",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "MirroringStaticProvisioning.RebootInitiator failed because mirror count was set to 4, should be between 1 and 3.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43753.0,
        "Build": "9.9.1(183-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5938",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "ResourceQuota.ResourceStaticPersistentVolumeClaims",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43754.0,
        "Build": "9.9.1(181-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5997",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43757.0,
        "Build": "9.9.1(188-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6012, DWS-6013",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43761.0,
        "Build": "9.9.1(193-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6034",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "VolumeRestore.NegativeTestsOnMirroredVolume",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43762.0,
        "Build": "9.9.1(198-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Expected and actual error message mistmatch for volume restore failure, but working for now so ignored this time",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43763.0,
        "Build": "9.9.1(199-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "Internal error occurred: Internal error occurred: etcd service unavailable, retry, err: context deadline exceeded\",",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43764.0,
        "Build": "9.9.1(200-0)",
        "Setup": "appserv53-55",
        "Result": "Pass",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43765.0,
        "Build": "9.9.1(204-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6050",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43766.0,
        "Build": "9.9.1(204-1)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6053",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "DeleteStaleStorageResources() fail to delete snapshots and LCVs recursively",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43766.0,
        "Build": "9.9.1(204-1)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6053",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "DeleteStaleStorageResources() fail to delete snapshots and LCVs recursively",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43766.0,
        "Build": "9.9.1(204-2)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6053",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "DeleteStaleStorageResources() fail to delete snapshots and LCVs recursively",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43768.0,
        "Build": "9.9.1(205-0)",
        "Setup": "appserv53-55",
        "Result": "Pass",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43768.0,
        "Build": "2.3.0(1-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6062",
        "Regression": "",
        "Part of Dev Sanity": "",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43769.0,
        "Build": "2.3.0(2-0)",
        "Setup": "appserv53-55",
        "Result": "Pass",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43770.0,
        "Build": "2.3.0(3-0)",
        "Setup": "appserv53-55",
        "Result": "Pass",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43770.0,
        "Build": "2.3.0(4-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-4613",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "\"too many open files\" in bosun",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43771.0,
        "Build": "2.3.0(5-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6074",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "ipmi status is on of appserv55 node, but not able to check status of ssh port",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43771.0,
        "Build": "2.3.0(5-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6074",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "ipmi status is on of appserv55 node, but not able to check status of ssh port",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43772.0,
        "Build": "2.3.0(6-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6074",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "ipmi status is on of appserv55 node, but not able to check status of ssh port",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43772.0,
        "Build": "2.3.0(6-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6074",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "ipmi status is on of appserv55 node, but not able to check status of ssh port",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43773.0,
        "Build": "2.3.0(7-0)",
        "Setup": "appserv53-55",
        "Result": "Pass",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43773.0,
        "Build": "2.3.0(7-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5764",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43774.0,
        "Build": "2.3.0(8-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "Techsupport did not get collected due to space issues on testserver3.\nThe possible reason, for this issue is convoy might be down when user fire dctl command to get endpoint.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43775.0,
        "Build": "2.3.0(9-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5764",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "network IPs/endpoint and NW bandwidth reservations were not released after pod deletion",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43775.0,
        "Build": "2.3.0(9-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "This commit 5e835204cb4493d171889f103c398512c2ca2a12 has broken sanity \nAuthor: sushil <sushil@diamanti.com>",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43775.0,
        "Build": "2.3.0(9-1)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "This commit 5e835204cb4493d171889f103c398512c2ca2a12 has broken sanity \nAuthor: sushil <sushil@diamanti.com>",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43776.0,
        "Build": "2.3.0(12-0)",
        "Setup": "appserv53-55",
        "Result": "Pass",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43777.0,
        "Build": "2.3.0(13-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5764",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "network IPs/endpoint and NW bandwidth reservations were not released after pod deletion.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43777.0,
        "Build": "2.3.0(13-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5285",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "Failed to get expected throughput on remote volumes",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43777.0,
        "Build": "2.3.0(16-0)",
        "Setup": "appserv53-55",
        "Result": "Pass",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43778.0,
        "Build": "2.3.0(16-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6113",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Volume didn't move to Available state after detach",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43778.0,
        "Build": "2.3.0(16-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "Failed to check ssh port of appserv53",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43779.0,
        "Build": "2.3.0(17-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Failed to check ssh port of appserv53",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43779.0,
        "Build": "2.3.0(20-0)",
        "Setup": "appserv53-55",
        "Result": "Pass",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43780.0,
        "Build": "2.3.0(20-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6107",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "dctl cluster configure --master command failing",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43781.0,
        "Build": "2.3.0(21-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6127",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "Failed to migrate master from node1 to the node node2",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43782.0,
        "Build": "2.3.0(23-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6132",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "After cluster destroy found cluste-info.json on node",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43783.0,
        "Build": "2.3.0(25-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6132",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "After cluster destroy found cluste-info.json on node",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43783.0,
        "Build": "2.3.0(25-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5764",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "network IPs/endpoint and NW bandwidth reservations were not released after pod deletion.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43784.0,
        "Build": "2.3.0(28-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6132",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "After cluster destroy found cluste-info.json on node (Fix is available in #30 build)",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43784.0,
        "Build": "2.3.0(29-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-5764",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "network IPs/endpoint and NW bandwidth reservations were not released after pod deletion.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43785.0,
        "Build": "2.3.0 (31-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6053",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "DeleteStaleStorageResources() fail to delete snapshots and LCVs recursively",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43786.0,
        "Build": "2.3.0 (34-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Weekly",
        "Notes": "Somebody destroyed the cluster in the middle of running TC",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43786.0,
        "Build": "2.3.0 (34-1)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6114",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "Failed due to automation issue. node label not cleaned-up at the end of TC",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43787.0,
        "Build": "2.3.99-23",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "Failed due to Neha's change. Naveen reverted the commit",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43787.0,
        "Build": "2.3.99-24",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "Failed due to Neha's change. Naveen reverted the commit",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43787.0,
        "Build": "2.3.99-25",
        "Setup": "appserv53-55",
        "Result": "Passed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43788.0,
        "Build": "2.3.0-38",
        "Setup": "appserv53-55",
        "Result": "Passed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "skiplist='Network.PingWithDnsName|StorageKubeSnapshot.PatternVerificationOnLCV|Rbac.Multiple|PerfTier.CreateDeleteValidateQosWithCustomMaxBwLimit|PerfTier.NetworkThroughputValidationCustomPerfTierWithMaxBWLimit|DirectionalOnePort|Rbac.SecureAuthLinuxLDAP'",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43788.0,
        "Build": "2.3.99-29",
        "Setup": "appserv53-55",
        "Result": "Passed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43792.0,
        "Build": "2.3.0 (48-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6078",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "User authentication failed with error invalid credentials",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43793.0,
        "Build": "2.3.0 (50-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6078",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "User authentication failed with error invalid credentials",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43794.0,
        "Build": "2.3.0 (51-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6078",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "User authentication failed with error invalid credentials",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43795.0,
        "Build": "2.3.0 (52-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "Automation issue. Need to fix CheckStaleResources function. Fix checked-in today",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43796.0,
        "Build": "2.3.0 (55-0)",
        "Setup": "appserv53-55",
        "Result": "Passed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "skiplist='Network.PingWithDnsName|StorageKubeSnapshot.PatternVerificationOnLCV|Rbac.Multiple|PerfTier.CreateDeleteValidateQosWithCustomMaxBwLimit|PerfTier.NetworkThroughputValidationCustomPerfTierWithMaxBWLimit|DirectionalOnePort|Rbac.SecureAuthLinuxLDAP'",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43797.0,
        "Build": "2.3.0 (56-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6246",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "Automation issue. Need to fix Volume restore TCs",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43798.0,
        "Build": "2.3.0 (58-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "Conflict due to http://gitlab.eng.diamanti.com/software/main/commit/a4dc17de1b8a951a7f446ab6f185d9b428f26638  ",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43567.0,
        "Build": "2.3.0(58-1)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6253",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "User login failed with single domain with error message: invalid credentials",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43628.0,
        "Build": "2.3.0(63-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "User login failed with single domain with error message: invalid credentials, due to internal servers were down.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43658.0,
        "Build": "2.3.0(64-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6272",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "\"dctl volume update\" now requires y/n option to update the volume",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43689.0,
        "Build": "2.3.0(64-1)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6272",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "\"dctl volume update\" now requires y/n option to update the volume",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43720.0,
        "Build": "2.3.0(64-2)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6253",
        "Regression": "",
        "Part of Dev Sanity": "Sanity|Daily",
        "Notes": "User login failed with single domain with error message: invalid credentials",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43720.0,
        "Build": "2.3.0(65-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6283",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "Need more logs to related to timestamp.",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43750.0,
        "Build": "2.3.0(66-0)",
        "Setup": "appserv53-55",
        "Result": "Passed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43750.0,
        "Build": "2.3.0(67-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6290",
        "Regression": "",
        "Part of Dev Sanity": "Daily",
        "Notes": "Group creation failed, with Error \"Cannot find cluster config, use `dctl -s <vip or fqdn> login`\")",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43781.0,
        "Build": "2.3.0(70-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Daily",
        "Notes": "Conflict : more than one spec file for same pod in directory",
        "Current Owner of Sanity": ""
    },
    {
        "Date": 43811.0,
        "Build": "2.3.0(74-0)",
        "Setup": "appserv53-55",
        "Result": "Passed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Daily",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "13/12/2019",
        "Build": "2.3.0(77-0)",
        "Setup": "appserv53-55",
        "Result": "Passed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "13/12/2019",
        "Build": "2.3.0(76-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6314",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "failed to generate device list because of temperature exceeded of the node",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "13/12/2019",
        "Build": "2.3.0(77-0)",
        "Setup": "appserv(53-55)",
        "Result": "Failed",
        "Bug": "DWS-6316",
        "Regression": "",
        "Part of Dev Sanity": "Daily",
        "Notes": "Failed to ping external IP from a pod created using Public network",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "15/12/2019",
        "Build": "2.3.0(81-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6319",
        "Regression": "",
        "Part of Dev Sanity": "Daily",
        "Notes": "Ping related issue",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "15/12/2019",
        "Build": "2.3.0(81-1)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6319",
        "Regression": "",
        "Part of Dev Sanity": "Daily",
        "Notes": "Failed to ping external IP from a pod created using Public network",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "16/12/2019",
        "Build": "2.3.0(83-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-6057",
        "Regression": "",
        "Part of Dev Sanity": "Sanity",
        "Notes": "Failed TC: Benchmarking.WriteThroughputRemoteVolumes\nReason: Timestamp of \"embedded uptime\" not matching on one of the nodes",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "17/12/2019",
        "Build": "2.3.0(83-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-4149",
        "Regression": "",
        "Part of Dev Sanity": "Daily",
        "Notes": "Failed TC: LocalStorage.ConfigStress\nReason: Failed to attach volumes to cluster nodes in iteration number: 3",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "17-12-2019",
        "Build": "2.3.0(84-0)",
        "Setup": "appserv53-55",
        "Result": "Passed",
        "Bug": "",
        "Regression": "",
        "Part of Dev Sanity": "Daily",
        "Notes": "",
        "Current Owner of Sanity": ""
    },
    {
        "Date": "18-12-2019",
        "Build": "2.3.0(85-0)",
        "Setup": "appserv53-55",
        "Result": "Failed",
        "Bug": "DWS-2276",
        "Regression": "",
        "Part of Dev Sanity": "Daily",
        "Notes": "Failed TC: Snapshot.RebootOneTarget. Reason: Failed to initialise Cookie Jar.",
        "Current Owner of Sanity": ""
    }
]